### ISSUE TITLE
Menu Item Missing

### ISSUE THREAD

**Issue by bnb** [antivanov/Brackets-Command-Line-Shortcuts#6] opened 2015-01-30 02:20 UTC
I installed the plugin, forgot about it, and later opened the shortcuts file from the Edit menu. I commented out the commands already inside, and then started writing a command. I deleted it, saved the file, and closed with the old commands still commented out. I closed Brackets. I reopened it later, and looked for the menu item, but it was gone.

I went into the Extensions Manager, and was looking for the extension to see if I still had it installed (I had uninstalled a bunch earlier), and I did, except where the Installed button was there was a little message that told me there was an error with the plugin. I unfortunately don't remember exactly what it said. There was a link next to it to uninstall, so I did. I restarted, reinstalled the plugin, restarted, and the menu is still gone, though there's no error message in the Extensions Manager.

Is there a way I can fix this? 

Here's my Developer Tools console log, though I looked through it and I don't think any of them have to do with this plugin: 

```
Download the React DevTools for a better development experience: http://fb.me/react-devtools
/C:/Users/Tierney/AppData/Roaming/Brackets/extensions/user/tjeffree.extensionhighlighter/main.js:221 Calling CSSStyleSheet.insertRule() with one argument is deprecated. Please pass the index argument as well: insertRule(x, 0).
/utils/EventDispatcher.js:100 Registering for deprecated event 'currentDocumentChange'. Instead, use MainViewManager.currentFileChange. Error
    at Object.on (/utils/EventDispatcher.js:100:43)
    at file:///C:/Users/Tierney/AppData/Roaming/Brackets/extensions/user/zeid.autosave-on-view-change/main.js:24:24
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.Module.enable (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1151:22)
    at Object.Module.init (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:782:26)
    at callGetModule (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1178:63)
    at Object.context.completeLoad (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1552:21)
    at HTMLScriptElement.context.onScriptLoad (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1679:29)
/command/KeyBindingManager.js:730 Cannot assign Ctrl-Alt-C to codefolding.collapse. It is already assigned to extension.commandline.run.3
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:87 NodeSocketTransport - start
/C:/Users/Tierney/AppData/Roaming/Brackets/extensions/user/brackets-html5codehints/main.js:523 AppInit
/utils/AppInit.js:95 Exception when calling a 'brackets done loading' handler: TypeError: number is not a function
/utils/AppInit.js:96 TypeError: number is not a function
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:290:33)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.add [as done] (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27169)
    at Object.d.always (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:28045)
    at Object.eval (/brackets.js:288:30)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.fireWith [as resolveWith] (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27673)
    at Object.e.(anonymous function) (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:28653)
/command/KeyBindingManager.js:730 Cannot assign Ctrl-Alt-B to io.emmet.balance_outward. It is already assigned to extension.commandline.run.0
/command/KeyBindingManager.js:730 Cannot assign Ctrl-Shift-Up to io.emmet.increment_number_by_1. It is already assigned to edit.lineUp
/command/KeyBindingManager.js:730 Cannot assign Ctrl-Shift-Down to io.emmet.decrement_number_by_1. It is already assigned to edit.lineDown
NodeDebugUtils.js:117 [node-log 9:19:31 PM] [36m[2015-01-29 21:19:31.719] [DEBUG] logfile - [39mStarted parent.
NodeDebugUtils.js:114 [node-error 9:19:31 PM] log4js.fileAppender - Writing to file \tmp\DiagnosticsDomain.log, error happened  { [Error: ENOENT, open 'C:\tmp\DiagnosticsDomain.log']
  errno: 34,
  code: 'ENOENT',
  path: 'C:\\tmp\\DiagnosticsDomain.log' }
```

**Comment by antivanov** [comment] 2015-02-01 20:47
Hi, the errors in the log are from other plugins. Some time ago Brackets had some backward incompatible changes that broke some plugins.

The menu item "Command Line Shortcuts" works for me, I am using Linux version of Brackets "Release 1.1 experimental build 1.1.0-15558 (release ea908cae5) 
build timestamp: Wed Dec 17 2014 13:00:52 GMT-0800"

Maybe you are using a newer version, can, you, please, provide the version number of Brackets you are using? The plugin itself was updated a few weeks ago.

**Comment by bnb** [comment] 2015-02-01 22:42
```
Release 1.1 build 1.1.0-15558 (release ea908cae5) 
build timestamp: Wed Dec 17 2014 12:51:02 GMT-0800
```
That's from the about Brackets. Looks like its similar, but not the exact same. (The build timestamp is different--does that matter?)

**Comment by antivanov** [comment] 2015-02-01 22:52
As a workaround you can edit the command line shortcuts configuration file in the extensions folder "Help" -> "Show Extensions Folder". 

It is a bit strange that I can still access the configuration via "Edit" -> "Command Line Shortcuts". Maybe it is because some other plugin is installed and that plugin registers some action with the  shortcut Ctrl+Shift+Q. 

Can you access the configuration by using the shortcut Ctrl+Shift+Q? If not, can you, please, provide the log right after that? This can help understanding what happens.

**Comment by bnb** [comment] 2015-02-04 20:27
Opening with `Ctrl` + `Shift` + `Q` worked. The menu is still not there. Here's the debug log, anyway:

```
/thirdparty/react.js:4356 Download the React DevTools for a better development experience: http://fb.me/react-devtools
/C:/Users/Tierney/AppData/Roaming/Brackets/extensions/user/tjeffree.extensionhighlighter/main.js:221 Calling CSSStyleSheet.insertRule() with one argument is deprecated. Please pass the index argument as well: insertRule(x, 0).
/command/KeyBindingManager.js:730 Cannot assign Ctrl-Alt-C to codefolding.collapse. It is already assigned to extension.commandline.run.3
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:87 NodeSocketTransport - start
/C:/Users/Tierney/AppData/Roaming/Brackets/extensions/user/brackets-html5codehints/main.js:523 AppInit
/utils/AppInit.js:95 Exception when calling a 'brackets done loading' handler: TypeError: number is not a function
/utils/AppInit.js:96 TypeError: number is not a function
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:290:33)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.add [as done] (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27169)
    at Object.d.always (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:28045)
    at Object.eval (/brackets.js:288:30)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.fireWith [as resolveWith] (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27673)
    at Object.e.(anonymous function) (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:28653)
/command/KeyBindingManager.js:730 Cannot assign Ctrl-Alt-B to io.emmet.balance_outward. It is already assigned to extension.commandline.run.0
/command/KeyBindingManager.js:730 Cannot assign Ctrl-Shift-Up to io.emmet.increment_number_by_1. It is already assigned to edit.lineUp
/command/KeyBindingManager.js:730 Cannot assign Ctrl-Shift-Down to io.emmet.decrement_number_by_1. It is already assigned to edit.lineDown
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 11:09:30 AM] [36m[2015-02-04 11:09:30.902] [DEBUG] logfile - [39mStarted parent.
extensions/default/DebugCommands/NodeDebugUtils.js:114 [node-error 11:09:30 AM] log4js.fileAppender - Writing to file \tmp\DiagnosticsDomain.log, error happened  { [Error: ENOENT, open 'C:\tmp\DiagnosticsDomain.log']
  errno: 34,
  code: 'ENOENT',
  path: 'C:\\tmp\\DiagnosticsDomain.log' }extensions/default/DebugCommands/NodeDebugUtils.js:114 handleLogEvent
```

**Comment by antivanov** [comment] 2015-02-09 19:14
In this log the errors are from two other extensions: tjeffree.extensionhighlighter and brackets-html5codehints. It may be that the menu item disappears because of other extensions, because so far I could not reproduce it. I will try to reproduce the issue again on another machine with a fresh Brackets installation, please, use the workaround for now and post an update if the problem was fixed.

**Comment by antivanov** [comment] 2015-03-27 23:11
Looks like the errors in the logs are not related to the Command Line shortcuts extensions. Closing the bug for now, please, reopen in case there is a strong evidence (logs) that the error was caused by this extension.

**Closed by antivanov** 2015-03-27 23:11 UTC
Labels: bug
